version: '3.8'

services:
  # FastAPI Backend
  api:
    build: .
    container_name: book-finder-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data:ro  # Read-only access to data
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn api.main_search:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  # Streamlit Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: book-finder-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    command: streamlit run streamlit_app_with_api.py --server.port=8501 --server.address=0.0.0.0

networks:
  default:
    name: book-finder-network